# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hypercore_bridge_pb2 as hypercore__bridge__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hypercore_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PriceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMidPrice = channel.unary_unary(
                '/hypercore.bridge.v1.PriceService/GetMidPrice',
                request_serializer=hypercore__bridge__pb2.MidPriceRequest.SerializeToString,
                response_deserializer=hypercore__bridge__pb2.MidPriceResponse.FromString,
                _registered_method=True)
        self.StreamMids = channel.unary_stream(
                '/hypercore.bridge.v1.PriceService/StreamMids',
                request_serializer=hypercore__bridge__pb2.StreamMidsRequest.SerializeToString,
                response_deserializer=hypercore__bridge__pb2.MidPriceResponse.FromString,
                _registered_method=True)
        self.GetBlockNumber = channel.unary_unary(
                '/hypercore.bridge.v1.PriceService/GetBlockNumber',
                request_serializer=hypercore__bridge__pb2.BlockNumberRequest.SerializeToString,
                response_deserializer=hypercore__bridge__pb2.BlockNumberResponse.FromString,
                _registered_method=True)


class PriceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMidPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PriceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMidPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMidPrice,
                    request_deserializer=hypercore__bridge__pb2.MidPriceRequest.FromString,
                    response_serializer=hypercore__bridge__pb2.MidPriceResponse.SerializeToString,
            ),
            'StreamMids': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMids,
                    request_deserializer=hypercore__bridge__pb2.StreamMidsRequest.FromString,
                    response_serializer=hypercore__bridge__pb2.MidPriceResponse.SerializeToString,
            ),
            'GetBlockNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockNumber,
                    request_deserializer=hypercore__bridge__pb2.BlockNumberRequest.FromString,
                    response_serializer=hypercore__bridge__pb2.BlockNumberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hypercore.bridge.v1.PriceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hypercore.bridge.v1.PriceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PriceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMidPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypercore.bridge.v1.PriceService/GetMidPrice',
            hypercore__bridge__pb2.MidPriceRequest.SerializeToString,
            hypercore__bridge__pb2.MidPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hypercore.bridge.v1.PriceService/StreamMids',
            hypercore__bridge__pb2.StreamMidsRequest.SerializeToString,
            hypercore__bridge__pb2.MidPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypercore.bridge.v1.PriceService/GetBlockNumber',
            hypercore__bridge__pb2.BlockNumberRequest.SerializeToString,
            hypercore__bridge__pb2.BlockNumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
