# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hypercore_bridge.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hypercore_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16hypercore_bridge.proto\x12\x13hypercore.bridge.v1\"\x1f\n\x0fMidPriceRequest\x12\x0c\n\x04\x63oin\x18\x01 \x01(\t\"L\n\x11StreamMidsRequest\x12\x0c\n\x04\x63oin\x18\x01 \x01(\t\x12\x14\n\x0csubscription\x18\x02 \x01(\t\x12\x13\n\x0bheartbeat_s\x18\x03 \x01(\x05\"_\n\x10MidPriceResponse\x12\x0c\n\x04\x63oin\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\r\n\x05ts_ms\x18\x03 \x01(\x03\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\t\"\x14\n\x12\x42lockNumberRequest\"A\n\x13\x42lockNumberResponse\x12\x0b\n\x03hex\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x04\x12\r\n\x05ts_ms\x18\x03 \x01(\x03\">\n\x19StreamLiquidationsRequest\x12\x0c\n\x04\x63oin\x18\x01 \x01(\t\x12\x13\n\x0bheartbeat_s\x18\x02 \x01(\x05\"\xbb\x01\n\x10LiquidationEvent\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0f\n\x07tx_hash\x18\x02 \x01(\t\x12\x14\n\x0c\x62lock_number\x18\x03 \x01(\x04\x12\x11\n\tlog_index\x18\x04 \x01(\r\x12\r\n\x05ts_ms\x18\x05 \x01(\x03\x12\x0e\n\x06source\x18\x06 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x07 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x08 \x01(\t\x12\x0e\n\x06topic0\x18\t \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\n \x01(\t2\x9d\x03\n\x0cPriceService\x12Z\n\x0bGetMidPrice\x12$.hypercore.bridge.v1.MidPriceRequest\x1a%.hypercore.bridge.v1.MidPriceResponse\x12]\n\nStreamMids\x12&.hypercore.bridge.v1.StreamMidsRequest\x1a%.hypercore.bridge.v1.MidPriceResponse0\x01\x12\x63\n\x0eGetBlockNumber\x12\'.hypercore.bridge.v1.BlockNumberRequest\x1a(.hypercore.bridge.v1.BlockNumberResponse\x12m\n\x12StreamLiquidations\x12..hypercore.bridge.v1.StreamLiquidationsRequest\x1a%.hypercore.bridge.v1.LiquidationEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hypercore_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MIDPRICEREQUEST']._serialized_start=47
  _globals['_MIDPRICEREQUEST']._serialized_end=78
  _globals['_STREAMMIDSREQUEST']._serialized_start=80
  _globals['_STREAMMIDSREQUEST']._serialized_end=156
  _globals['_MIDPRICERESPONSE']._serialized_start=158
  _globals['_MIDPRICERESPONSE']._serialized_end=253
  _globals['_BLOCKNUMBERREQUEST']._serialized_start=255
  _globals['_BLOCKNUMBERREQUEST']._serialized_end=275
  _globals['_BLOCKNUMBERRESPONSE']._serialized_start=277
  _globals['_BLOCKNUMBERRESPONSE']._serialized_end=342
  _globals['_STREAMLIQUIDATIONSREQUEST']._serialized_start=344
  _globals['_STREAMLIQUIDATIONSREQUEST']._serialized_end=406
  _globals['_LIQUIDATIONEVENT']._serialized_start=409
  _globals['_LIQUIDATIONEVENT']._serialized_end=596
  _globals['_PRICESERVICE']._serialized_start=599
  _globals['_PRICESERVICE']._serialized_end=1012
# @@protoc_insertion_point(module_scope)
